[build]
  publish = "_site"
  command = "curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run --unstable -A https://deno.land/x/lume/cli.js --location=https://deno-blog.netlify.app/"